[package]
name = "ship_parts"
version = "0.1.0"
authors = ["InnocentusLime <InnocentusLime.help@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab = "0.4.2"
tinyvec = "1.2.0"
cgmath = "0.18.0"
glium = "0.29.0"

std_ext = { path = "../std_ext" }
collision = { path = "../collision" }
sys_api = { path = "../sys_api" }
cgmath_ext = { path = "../cgmath_ext" }
