[package]
name = "solar_knight"
version = "0.1.0"
authors = ["innocentus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
cgmath = "*"
cfg-if = "*"
log = "*"
simplelog = "*"
glutin = "*"
glium = "*"
