[package]
name = "square_map"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# crates.io crates
float-ord = "0.3.1"
nalgebra = "0.29.0"
serde = { version = "1.0.123", features = ["derive"]}
# local modules
systems_core = { path = "../systems_core" }
ship_transform = { path = "../ship_transform" }
