[package]
name = "loaders"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
image = "0.23.14"
glium = "0.29.0"

pack = { path = "../pack" }
sys_api = { path = "../sys_api" }
