[package]
name = "ship_engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# crates.io crates
cgmath = { version = "0.18.0", features = ["serde"]}
serde = { version = "1.0.123", features = ["derive"]}
tinyvec = { version = "1.2.0", features = ["serde"]}
# local crates
systems_core = { path = "../systems_core" }
ship_transform = { path = "../ship_transform" }
physics = { path = "../physics" }
# external crates
cgmath_ext = { path = "../../../cgmath_ext" }
