[package]
name = "ship_transform"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# crates.io crates
nalgebra = "0.29.0"
# local crates
systems_core = { path = "../systems_core" }
# external crates
